#!/bin/bash
# 🎯 Multi-Car Interaction System - Complete Testing Guide
# This script provides step-by-step testing instructions

echo "🏎️ MULTI-CAR INTERACTION SYSTEM - TESTING GUIDE"
echo "=================================================================="
echo ""

echo "✅ PRE-REQUISITES:"
echo "  1. Package built successfully: catkin build multi_car_interaction"
echo "  2. Environment sourced: source devel/setup.bash"
echo "  3. Map files available in stack_master package"
echo ""

echo "🚀 STEP 1: LAUNCH ENHANCED MULTI-CAR SYSTEM"
echo "=================================================================="
echo "Command:"
echo "  roslaunch stack_master multi_car.launch \\"
echo "    global_map:=f \\"
echo "    sim:=True \\"
echo "    rviz:=True \\"
echo "    enable_car_interaction:=True \\"
echo "    enable_collision_detection:=True"
echo ""
echo "Expected Result:"
echo "  ✅ Both cars start in simulator"
echo "  ✅ Multi-car interaction nodes launch"
echo "  ✅ RViz opens with car visualization"
echo "  ✅ No error messages in terminal"
echo ""

echo "🔍 STEP 2: VERIFY OBSTACLE PUBLISHING"
echo "=================================================================="
echo "Commands to run in new terminal:"
echo "  # Check car1 sees car2 as obstacle"
echo "  rostopic echo /car1/perception/multi_car_obstacles"
echo ""
echo "  # Check car2 sees car1 as obstacle" 
echo "  rostopic echo /car2/perception/multi_car_obstacles"
echo ""
echo "  # Verify publishing rates"
echo "  rostopic hz /car1/perception/multi_car_obstacles"
echo "  rostopic hz /car2/perception/multi_car_obstacles"
echo ""
echo "Expected Result:"
echo "  ✅ ObstacleArray messages with Frenet coordinates"
echo "  ✅ Publishing rate around 20Hz"
echo "  ✅ s_center and d_center values changing as cars move"
echo "  ✅ vs (velocity) reflecting real car speeds"
echo ""

echo "📊 STEP 3: MONITOR COLLISION DETECTION"
echo "=================================================================="
echo "Commands:"
echo "  # Global collision status"
echo "  rostopic echo /multi_car/collision_status"
echo ""
echo "  # Individual car warnings"
echo "  rostopic echo /car1/collision_warning"
echo "  rostopic echo /car2/collision_warning"
echo ""
echo "Expected Result:"
echo "  ✅ collision_status: False (initially)"
echo "  ✅ warning_active: False (initially)"
echo "  ✅ distance values updating in real-time"
echo ""

echo "🎮 STEP 4: TEST COLLISION AVOIDANCE BEHAVIOR"
echo "=================================================================="
echo "Manual Test:"
echo "  1. In RViz, use '2D Nav Goal' to drive cars close together"
echo "  2. Set waypoints that would make cars intersect"
echo "  3. Observe car behavior in simulation"
echo ""
echo "Expected Behavior:"
echo "  ✅ Cars automatically avoid each other"
echo "  ✅ Collision warnings appear when cars get close"
echo "  ✅ Planning trajectories change to avoid collisions"
echo "  ✅ Cars don't drive through each other anymore"
echo ""

echo "🔧 STEP 5: VERIFY MESSAGE COMPATIBILITY"
echo "=================================================================="
echo "Commands:"
echo "  # Compare with dummy obstacles"
echo "  rosmsg show f110_msgs/ObstacleArray"
echo ""
echo "  # Check message structure"
echo "  rostopic echo -n1 /car1/perception/multi_car_obstacles | grep -E '(id|s_center|d_center|vs)'"
echo ""
echo "Expected Result:"
echo "  ✅ Same message format as dummy obstacles"
echo "  ✅ Frenet coordinates (s_center, d_center)"
echo "  ✅ Velocity data (vs, vd)"
echo "  ✅ Standard obstacle properties"
echo ""

echo "📈 STEP 6: PERFORMANCE VALIDATION"
echo "=================================================================="
echo "Commands:"
echo "  # Check system resource usage"
echo "  htop"
echo ""
echo "  # Monitor node status"
echo "  rosnode list | grep multi_car"
echo ""
echo "  # Check for any errors"
echo "  rosnode info /multi_car_obstacle_publisher"
echo "  rosnode info /car_collision_detector"
echo ""
echo "Expected Result:"
echo "  ✅ CPU usage <1% for multi-car nodes"
echo "  ✅ All multi-car nodes running"
echo "  ✅ No connection errors"
echo "  ✅ Smooth system operation"
echo ""

echo "🎯 STEP 7: ADVANCED TESTING"
echo "=================================================================="
echo "Racing Scenario Tests:"
echo "  1. Overtaking: Set car1 behind car2, verify overtaking behavior"
echo "  2. Head-on: Set cars on collision course, verify avoidance"
echo "  3. Side-by-side: Place cars adjacent, verify lane keeping"
echo "  4. Cornering: Test avoidance behavior in turns"
echo ""
echo "Parameter Tuning:"
echo "  # Adjust collision detection sensitivity"
echo "  rosparam set /multi_car_interaction/warning_distance 2.0"
echo "  rosparam set /multi_car_interaction/critical_distance 1.0"
echo ""
echo "Expected Advanced Results:"
echo "  ✅ Realistic racing dynamics"
echo "  ✅ Strategic overtaking behavior"
echo "  ✅ Defensive driving when blocked"
echo "  ✅ Smooth collision avoidance in all scenarios"
echo ""

echo "🐛 TROUBLESHOOTING GUIDE"
echo "=================================================================="
echo "Common Issues and Solutions:"
echo ""
echo "❌ No obstacles published:"
echo "  Solution: Check frenet conversion service"
echo "  Command: rosservice list | grep frenet"
echo ""
echo "❌ TF transform errors:"
echo "  Solution: Verify TF tree"
echo "  Command: rosrun tf view_frames && evince frames.pdf"
echo ""
echo "❌ Cars still drive through each other:"
echo "  Solution: Check planner subscriptions"
echo "  Command: rostopic info /car1/perception/multi_car_obstacles"
echo ""
echo "❌ Poor performance:"
echo "  Solution: Reduce publishing rate"
echo "  Command: rosparam set /multi_car_interaction/publish_rate 10.0"
echo ""

echo "✅ SUCCESS CRITERIA"
echo "=================================================================="
echo "System is working correctly when:"
echo "  🎯 Cars detect each other as obstacles"
echo "  🎯 Automatic collision avoidance behavior"
echo "  🎯 Realistic racing dynamics"
echo "  🎯 Real-time collision warnings"
echo "  🎯 Smooth performance (<1% CPU overhead)"
echo "  🎯 Zero modifications to existing nodes"
echo ""

echo "🎉 CONGRATULATIONS!"
echo "=================================================================="
echo "You now have a fully functional multi-car racing simulation with:"
echo "  ✅ Car-to-car perception"
echo "  ✅ Collision avoidance"
echo "  ✅ Realistic racing behavior"
echo "  ✅ Complete system integration"
echo ""
echo "🏁 Ready for advanced racing scenarios!"
