#!/usr/bin/env python3
"""
Data processing utilities for Marina map parser.
Supports both CSV (TAM format) and JSON (F1/10 global_waypoints.json) input.
"""
import json
import math
from typing import List, Dict, Any, Tuple
from config import Waypoint, CSVColumnMapping, MapConfig


class InputProcessor:
    """Handles CSV and JSON file loading and waypoint creation."""

    def __init__(self, config: MapConfig):
        self.config = config
        self.column_mapping = CSVColumnMapping.MAPPING

    def load_data(self) -> Dict[str, List[Waypoint]]:
        """Load and parse input file (CSV or JSON) into waypoints."""
        if self.config.input_type == 'csv':
            return self.load_csv_data()
        elif self.config.input_type == 'json':
            return self.load_json_data()
        else:
            raise ValueError(
                f"Unsupported input type: {self.config.input_type}")

    def load_csv_data(self) -> Dict[str, List[Waypoint]]:
        """Load and parse CSV file into waypoints."""
        print(f"Loading Marina CSV: {self.config.input_file}")

        # Read CSV, skip header lines
        data_lines = self._read_csv_lines()
        print(f"Found {len(data_lines)} data lines")

        # Parse waypoints
        waypoints = self._parse_waypoints(data_lines)

        # Validate track closure
        self._validate_track_closure(waypoints)

        # Print statistics
        self._print_track_statistics(waypoints)

        return waypoints

    def load_json_data(self) -> Dict[str, List[Waypoint]]:
        """Load and parse JSON file (global_waypoints.json) into waypoints."""
        print(f"Loading F1/10 JSON: {self.config.input_file}")

        with open(self.config.input_file, 'r') as f:
            data = json.load(f)

        # Extract centerline waypoints
        centerline_waypoints = self._parse_json_centerline(data)

        # Extract track boundaries and convert to both formats
        trackbounds_left, trackbounds_right = self._parse_json_trackbounds_as_waypoints(
            data, centerline_waypoints)

        # Calculate track widths from boundaries (use simple boundary points for width calculation)
        trackbounds_raw = self._parse_json_trackbounds(data)
        self._calculate_track_widths(centerline_waypoints, trackbounds_raw)

        # Check for existing racing line (global trajectory)
        iqp_waypoints = self._parse_json_racing_line(data)

        # Print statistics
        self._print_json_statistics(
            centerline_waypoints, iqp_waypoints, trackbounds_raw)

        return {
            'centerline': centerline_waypoints,
            'iqp': iqp_waypoints,
            'trackbounds_left': trackbounds_left,
            'trackbounds_right': trackbounds_right,
        }

    def _read_csv_lines(self) -> List[str]:
        """Read CSV file and filter out header lines."""
        data_lines = []
        with open(self.config.input_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    data_lines.append(line)
        return data_lines

    def _parse_waypoints(self, data_lines: List[str]) -> Dict[str, List[Waypoint]]:
        """Parse CSV lines into waypoint objects."""
        centerline_waypoints = []
        iqp_waypoints = []
        trackbounds_left = []
        trackbounds_right = []
        # SP will be generated by trajectory generator, not loaded from CSV

        # Skip header line (first line contains column names)
        for i, line in enumerate(data_lines[1:], start=0):
            values = line.split(',')
            if len(values) < max(self.column_mapping.values()) + 1:
                continue

            # Always create centerline waypoint (reference data is always available)
            centerline_waypoints.append(
                self._create_centerline_waypoint(values, i))

            # Only create IQP waypoint if racing line data is valid
            iqp_waypoint = self._try_create_iqp_waypoint(
                values, len(iqp_waypoints))
            if iqp_waypoint:
                iqp_waypoints.append(iqp_waypoint)

            # Extract trackbounds if available (need at least 46 columns)
            if len(values) >= 46:
                try:
                    # Left trackbound (columns 41-42: tb_left_x_ref_rl_m, tb_left_y_ref_rl_m)
                    left_x = float(values[41])
                    left_y = float(values[42])

                    # Right trackbound (columns 44-45: tb_right_x_ref_rl_m, tb_right_y_ref_rl_m)
                    right_x = float(values[44])
                    right_y = float(values[45])

                    # Create waypoints for trackbounds (no scaling applied here)
                    left_waypoint = Waypoint(
                        id=i, s_m=0.0, d_m=0.0, x_m=left_x, y_m=left_y,
                        d_right=0.0, d_left=0.0, psi_rad=0.0,
                        kappa_radpm=0.0, vx_mps=0.0, ax_mps2=0.0
                    )
                    right_waypoint = Waypoint(
                        id=i, s_m=0.0, d_m=0.0, x_m=right_x, y_m=right_y,
                        d_right=0.0, d_left=0.0, psi_rad=0.0,
                        kappa_radpm=0.0, vx_mps=0.0, ax_mps2=0.0
                    )

                    trackbounds_left.append(left_waypoint)
                    trackbounds_right.append(right_waypoint)

                except (ValueError, IndexError):
                    # Skip invalid trackbound data
                    pass

        print(f"✓ Parsed {len(centerline_waypoints)} centerline waypoints")
        print(f"✓ Parsed {len(iqp_waypoints)} racing line (IQP) waypoints")
        print(f"✓ Extracted {len(trackbounds_left)} left trackbounds")
        print(f"✓ Extracted {len(trackbounds_right)} right trackbounds")

        # If racing line is shorter, print warning
        if len(iqp_waypoints) < len(centerline_waypoints):
            print(
                f"⚠ Racing line data ends at waypoint {len(iqp_waypoints)}, centerline continues to {len(centerline_waypoints)}")

        return {
            'centerline': centerline_waypoints,
            'iqp': iqp_waypoints,
            'trackbounds_left': trackbounds_left,
            'trackbounds_right': trackbounds_right,
            # SP will be generated by trajectory generator
        }

    def _create_centerline_waypoint(self, values: List[str], waypoint_id: int) -> Waypoint:
        """Create centerline waypoint from CSV values."""
        x_m = self._safe_float(values[self.column_mapping['ref_cl_x_m']])
        y_m = self._safe_float(values[self.column_mapping['ref_cl_y_m']])
        s_m = self._safe_float(values[self.column_mapping['ref_cl_s_m']])
        psi_rad = self._safe_float(
            values[self.column_mapping['ref_cl_psi_rad']])
        kappa_radpm = self._safe_float(
            values[self.column_mapping['ref_cl_kappa_radpm']])

        # Apply width multiplier
        d_right = abs(self._safe_float(
            values[self.column_mapping['ref_cl_d_right']], 2.0)) * self.config.width_multiplier
        d_left = abs(self._safe_float(
            values[self.column_mapping['ref_cl_d_left']], 2.0)) * self.config.width_multiplier

        # Conservative speed based on curvature
        vx_mps = self._calculate_conservative_speed(kappa_radpm)

        return Waypoint(
            id=waypoint_id, s_m=s_m, d_m=0.0, x_m=x_m, y_m=y_m,
            d_right=d_right, d_left=d_left, psi_rad=psi_rad,
            kappa_radpm=kappa_radpm, vx_mps=vx_mps, ax_mps2=0.0
        )

    def _try_create_iqp_waypoint(self, values: List[str], waypoint_id: int) -> Waypoint:
        """Create IQP waypoint from CSV values, return None if racing line data is invalid."""
        # Check if racing line data is valid (not NaN/empty)
        x_m_str = values[self.column_mapping['rl_x_m']].strip()
        y_m_str = values[self.column_mapping['rl_y_m']].strip()

        # Skip if racing line coordinates are NaN, empty, or invalid
        if (x_m_str.lower() == 'nan' or x_m_str == '' or
                y_m_str.lower() == 'nan' or y_m_str == ''):
            return None

        try:
            x_m = float(x_m_str)
            y_m = float(y_m_str)

            # Skip if coordinates are NaN after conversion
            if math.isnan(x_m) or math.isnan(y_m):
                return None

        except (ValueError, TypeError):
            return None

        # If we get here, racing line data is valid - proceed with creation
        psi_rad = self._safe_float(values[self.column_mapping['rl_psi_rad']])
        vx_mps = self._safe_float(
            values[self.column_mapping['rl_vx_mps']], 15.0)
        ax_mps2 = self._safe_float(
            values[self.column_mapping['rl_ax_mps2']], 0.0)

        s_m = self._safe_float(values[self.column_mapping['ref_rl_s_m']])
        kappa_radpm = self._safe_float(
            values[self.column_mapping['ref_rl_kappa_radpm']])

        # Apply width multiplier
        d_right = abs(self._safe_float(
            values[self.column_mapping['ref_rl_d_right']], 2.0)) * self.config.width_multiplier
        d_left = abs(self._safe_float(
            values[self.column_mapping['ref_rl_d_left']], 2.0)) * self.config.width_multiplier

        return Waypoint(
            id=waypoint_id, s_m=s_m, d_m=0.0, x_m=x_m, y_m=y_m,
            d_right=d_right, d_left=d_left, psi_rad=psi_rad,
            kappa_radpm=kappa_radpm, vx_mps=vx_mps, ax_mps2=ax_mps2
        )

    def _create_iqp_waypoint(self, values: List[str], waypoint_id: int) -> Waypoint:
        """Create IQP waypoint from CSV values."""
        # Try racing line data first, fallback to centerline
        x_m = self._safe_float(values[self.column_mapping['rl_x_m']])
        y_m = self._safe_float(values[self.column_mapping['rl_y_m']])

        if x_m == 0.0 and y_m == 0.0:
            x_m = self._safe_float(values[self.column_mapping['ref_cl_x_m']])
            y_m = self._safe_float(values[self.column_mapping['ref_cl_y_m']])

        psi_rad = self._safe_float(values[self.column_mapping['rl_psi_rad']])
        if psi_rad == 0.0:
            psi_rad = self._safe_float(
                values[self.column_mapping['ref_cl_psi_rad']])

        vx_mps = self._safe_float(
            values[self.column_mapping['rl_vx_mps']], 15.0)
        ax_mps2 = self._safe_float(
            values[self.column_mapping['rl_ax_mps2']], 0.0)

        s_m = self._safe_float(values[self.column_mapping['ref_rl_s_m']])
        if s_m == 0.0:
            s_m = self._safe_float(values[self.column_mapping['ref_cl_s_m']])

        kappa_radpm = self._safe_float(
            values[self.column_mapping['ref_rl_kappa_radpm']])
        if kappa_radpm == 0.0:
            kappa_radpm = self._safe_float(
                values[self.column_mapping['ref_cl_kappa_radpm']])

        # Apply width multiplier with fallback
        d_right = abs(self._safe_float(
            values[self.column_mapping['ref_rl_d_right']], 0.0)) * self.config.width_multiplier
        d_left = abs(self._safe_float(
            values[self.column_mapping['ref_rl_d_left']], 0.0)) * self.config.width_multiplier

        if d_right == 0.0:
            d_right = abs(self._safe_float(
                values[self.column_mapping['ref_cl_d_right']], 2.0)) * self.config.width_multiplier
        if d_left == 0.0:
            d_left = abs(self._safe_float(
                values[self.column_mapping['ref_cl_d_left']], 2.0)) * self.config.width_multiplier

        return Waypoint(
            id=waypoint_id, s_m=s_m, d_m=0.0, x_m=x_m, y_m=y_m,
            d_right=d_right, d_left=d_left, psi_rad=psi_rad,
            kappa_radpm=kappa_radpm, vx_mps=vx_mps, ax_mps2=ax_mps2
        )

    def _safe_float(self, value_str: str, default: float = 0.0) -> float:
        """Safely convert string to float."""
        try:
            val = float(value_str)
            return val if not math.isnan(val) else default
        except (ValueError, TypeError):
            return default

    def _calculate_conservative_speed(self, kappa_radpm: float) -> float:
        """Calculate conservative speed based on curvature."""
        base_speed = 15.0
        min_speed = 5.0
        abs_curvature = abs(kappa_radpm)

        if abs_curvature > 0.001:
            return max(min_speed, base_speed * (1.0 - abs_curvature * 50.0))
        return base_speed

    def _validate_track_closure(self, waypoints: Dict[str, List[Waypoint]]):
        """Validate track closure for all trajectory types."""
        print("\n=== Track Closure Validation ===")

        for traj_name, wps in waypoints.items():
            if not wps:
                continue

            first, last = wps[0], wps[-1]
            distance = math.sqrt((last.x_m - first.x_m) **
                                 2 + (last.y_m - first.y_m)**2)

            print(f"{traj_name}: distance between start/end = {distance:.3f}m")
            if distance < 5.0:
                print(f"✓ {traj_name} track is properly closed")
            else:
                print(f"WARNING: {traj_name} track is not properly closed!")
                print(f"First point: ({first.x_m:.2f}, {first.y_m:.2f})")
                print(f"Last point:  ({last.x_m:.2f}, {last.y_m:.2f})")

        print("==========================================\n")

    def _print_track_statistics(self, waypoints: Dict[str, List[Waypoint]]):
        """Print track width statistics."""
        centerline_wps = waypoints.get('centerline', [])
        if not centerline_wps:
            return

        print("=== Track Width Statistics (with width multiplier applied) ===")
        print(f"Width multiplier: {self.config.width_multiplier}x")

        right_widths = [wp.d_right for wp in centerline_wps]
        left_widths = [wp.d_left for wp in centerline_wps]
        total_widths = [wp.d_right + wp.d_left for wp in centerline_wps]

        print(
            f"Right bounds:  min={min(right_widths):.2f}m, max={max(right_widths):.2f}m, avg={sum(right_widths)/len(right_widths):.2f}m")
        print(
            f"Left bounds:   min={min(left_widths):.2f}m, max={max(left_widths):.2f}m, avg={sum(left_widths)/len(left_widths):.2f}m")
        print(
            f"Total width:   min={min(total_widths):.2f}m, max={max(total_widths):.2f}m, avg={sum(total_widths)/len(total_widths):.2f}m")
        print("================================================================\n")

    # JSON input processing methods
    def _parse_json_centerline(self, data: Dict[str, Any]) -> List[Waypoint]:
        """Parse centerline waypoints from F1/10 JSON format."""
        if 'centerline_waypoints' not in data or 'wpnts' not in data['centerline_waypoints']:
            raise ValueError(
                "JSON missing required centerline_waypoints.wpnts data")

        waypoints = []
        wpnts = data['centerline_waypoints']['wpnts']

        for wp_data in wpnts:
            # Extract required fields
            waypoint_id = wp_data.get('id', len(waypoints))
            s_m = wp_data.get('s_m', 0.0)
            x_m = wp_data.get('x_m', 0.0)
            y_m = wp_data.get('y_m', 0.0)

            # Calculate heading from consecutive waypoints (if available)
            psi_rad = 0.0  # Will be calculated later if needed
            kappa_radpm = 0.0  # Will be calculated later if needed

            # Set conservative speed
            vx_mps = self._calculate_conservative_speed(kappa_radpm)

            waypoint = Waypoint(
                id=waypoint_id, s_m=s_m, d_m=0.0, x_m=x_m, y_m=y_m,
                d_right=2.0, d_left=2.0,  # Will be updated with trackbounds
                psi_rad=psi_rad, kappa_radpm=kappa_radpm,
                vx_mps=vx_mps, ax_mps2=0.0
            )
            waypoints.append(waypoint)

        print(f"✓ Parsed {len(waypoints)} centerline waypoints from JSON")
        return waypoints

    def _parse_json_trackbounds(self, data: Dict[str, Any]) -> List[Dict[str, float]]:
        """Parse track boundary points from F1/10 JSON format."""
        if 'trackbounds_markers' not in data or 'markers' not in data['trackbounds_markers']:
            print(
                "⚠ JSON missing trackbounds_markers.markers - using default track widths")
            return []

        boundaries = []
        markers = data['trackbounds_markers']['markers']

        for marker in markers:
            if 'pose' in marker and 'position' in marker['pose']:
                pos = marker['pose']['position']
                boundaries.append({
                    'x': pos.get('x', 0.0),
                    'y': pos.get('y', 0.0)
                })

        print(f"✓ Extracted {len(boundaries)} track boundary points")
        return boundaries

    def _parse_json_trackbounds_as_waypoints(self, data: Dict[str, Any], centerline_waypoints: List[Waypoint]) -> Tuple[List[Waypoint], List[Waypoint]]:
        """Parse track boundary points from F1/10 JSON format and convert to Waypoint lists (same format as CSV)."""
        if 'trackbounds_markers' not in data or 'markers' not in data['trackbounds_markers']:
            print("⚠ JSON missing trackbounds_markers.markers - using empty trackbounds")
            return [], []

        # Get raw boundary points
        raw_boundaries = []
        markers = data['trackbounds_markers']['markers']

        for marker in markers:
            if 'pose' in marker and 'position' in marker['pose']:
                pos = marker['pose']['position']
                raw_boundaries.append({
                    'x': pos.get('x', 0.0),
                    'y': pos.get('y', 0.0)
                })

        if len(raw_boundaries) < 4 or not centerline_waypoints:
            print(
                "⚠ Insufficient trackbounds or centerline data - using empty trackbounds")
            return [], []

        # Use centerline waypoints to properly classify left/right boundaries
        left_points = []   # Left side of track (looking forward)
        right_points = []  # Right side of track (looking forward)

        for boundary in raw_boundaries:
            # Find closest centerline waypoint to this boundary point
            min_distance = float('inf')
            closest_cl_idx = 0

            for i, cl_wp in enumerate(centerline_waypoints):
                dist = math.sqrt(
                    (boundary['x'] - cl_wp.x_m)**2 + (boundary['y'] - cl_wp.y_m)**2)
                if dist < min_distance:
                    min_distance = dist
                    closest_cl_idx = i

            # Get centerline direction at closest point
            cl_wp = centerline_waypoints[closest_cl_idx]

            # Calculate heading from consecutive centerline points if psi_rad is not available
            if cl_wp.psi_rad != 0.0:
                heading = cl_wp.psi_rad
            else:
                # Calculate heading from next waypoint
                next_idx = (closest_cl_idx + 1) % len(centerline_waypoints)
                next_wp = centerline_waypoints[next_idx]
                heading = math.atan2(
                    next_wp.y_m - cl_wp.y_m, next_wp.x_m - cl_wp.x_m)

            # Vector from centerline to boundary point
            to_boundary_x = boundary['x'] - cl_wp.x_m
            to_boundary_y = boundary['y'] - cl_wp.y_m

            # Calculate cross product to determine left/right side
            # Cross product of forward direction and to_boundary vector
            forward_x = math.cos(heading)
            forward_y = math.sin(heading)

            # Cross product: forward × to_boundary
            cross_product = forward_x * to_boundary_y - forward_y * to_boundary_x

            # Positive cross product means left side, negative means right side
            if cross_product > 0:
                left_points.append((boundary['x'], boundary['y']))
            else:
                right_points.append((boundary['x'], boundary['y']))

        # Sort points by their position along the track
        def sort_by_track_position(points):
            """Sort boundary points by their position along the centerline."""
            sorted_points = []
            for x, y in points:
                # Find closest centerline point again for sorting
                min_distance = float('inf')
                closest_s = 0.0

                for cl_wp in centerline_waypoints:
                    dist = math.sqrt((x - cl_wp.x_m)**2 + (y - cl_wp.y_m)**2)
                    if dist < min_distance:
                        min_distance = dist
                        closest_s = cl_wp.s_m

                sorted_points.append((x, y, closest_s))

            # Sort by s coordinate along track
            sorted_points.sort(key=lambda p: p[2])
            return [(p[0], p[1]) for p in sorted_points]

        left_points = sort_by_track_position(left_points)
        right_points = sort_by_track_position(right_points)

        # Convert to Waypoint objects (same format as CSV)
        trackbounds_left = []
        trackbounds_right = []

        for i, (x, y) in enumerate(left_points):
            waypoint = Waypoint(
                id=i, s_m=0.0, d_m=0.0, x_m=x, y_m=y,
                d_right=0.0, d_left=0.0, psi_rad=0.0,
                kappa_radpm=0.0, vx_mps=0.0, ax_mps2=0.0
            )
            trackbounds_left.append(waypoint)

        for i, (x, y) in enumerate(right_points):
            waypoint = Waypoint(
                id=i, s_m=0.0, d_m=0.0, x_m=x, y_m=y,
                d_right=0.0, d_left=0.0, psi_rad=0.0,
                kappa_radpm=0.0, vx_mps=0.0, ax_mps2=0.0
            )
            trackbounds_right.append(waypoint)

        print(
            f"✓ Extracted {len(trackbounds_left)} left trackbounds as waypoints")
        print(
            f"✓ Extracted {len(trackbounds_right)} right trackbounds as waypoints")

        return trackbounds_left, trackbounds_right

    def _parse_json_racing_line(self, data: Dict[str, Any]) -> List[Waypoint]:
        """Parse racing line (global trajectory) from F1/10 JSON format."""
        # Try IQP trajectory first
        if 'global_traj_wpnts_iqp' in data and 'wpnts' in data['global_traj_wpnts_iqp']:
            return self._parse_json_trajectory(data['global_traj_wpnts_iqp']['wpnts'], 'IQP')

        # Try SP trajectory as fallback
        if 'global_traj_wpnts_sp' in data and 'wpnts' in data['global_traj_wpnts_sp']:
            return self._parse_json_trajectory(data['global_traj_wpnts_sp']['wpnts'], 'SP')

        print("⚠ No global trajectory found in JSON - will generate racing line")
        return []

    def _parse_json_trajectory(self, wpnts: List[Dict], traj_type: str) -> List[Waypoint]:
        """Parse a trajectory from JSON waypoint data."""
        waypoints = []

        for wp_data in wpnts:
            waypoint_id = wp_data.get('id', len(waypoints))
            s_m = wp_data.get('s_m', 0.0)
            x_m = wp_data.get('x_m', 0.0)
            y_m = wp_data.get('y_m', 0.0)
            vx_mps = wp_data.get('vx_mps', 15.0)
            ax_mps2 = wp_data.get('ax_mps2', 0.0)

            # Try to get geometric data
            psi_rad = wp_data.get('psi_rad', 0.0)
            kappa_radpm = wp_data.get('kappa_radpm', 0.0)

            waypoint = Waypoint(
                id=waypoint_id, s_m=s_m, d_m=0.0, x_m=x_m, y_m=y_m,
                d_right=2.0, d_left=2.0,  # Will be updated with trackbounds
                psi_rad=psi_rad, kappa_radpm=kappa_radpm,
                vx_mps=vx_mps, ax_mps2=ax_mps2
            )
            waypoints.append(waypoint)

        print(
            f"✓ Parsed {len(waypoints)} {traj_type} racing line waypoints from JSON")
        return waypoints

    def _calculate_track_widths(self, centerline: List[Waypoint], boundaries: List[Dict[str, float]]):
        """Calculate track widths by finding closest boundary points to each centerline point."""
        if not boundaries:
            # Use default widths with multiplier
            default_width = 2.0 * self.config.width_multiplier
            for wp in centerline:
                wp.d_right = default_width
                wp.d_left = default_width
            return

        for wp in centerline:
            # Find closest boundary points to this centerline point
            distances = []
            for boundary in boundaries:
                dist = math.sqrt(
                    (wp.x_m - boundary['x'])**2 + (wp.y_m - boundary['y'])**2)
                distances.append(dist)

            if distances:
                # Use closest boundary distance as track width estimate
                min_dist = min(distances)
                # Apply width multiplier and use as both left and right width
                track_width = min_dist * self.config.width_multiplier
                wp.d_right = track_width
                wp.d_left = track_width

    def _print_json_statistics(self, centerline: List[Waypoint], racing_line: List[Waypoint], boundaries: List[Dict]):
        """Print statistics for JSON-loaded data."""
        print("\n=== JSON Data Statistics ===")
        print(f"Centerline waypoints: {len(centerline)}")
        print(f"Racing line waypoints: {len(racing_line)}")
        print(f"Track boundary points: {len(boundaries)}")

        if centerline:
            print(f"Track length: ~{centerline[-1].s_m:.1f}m")

        # Print track width statistics using existing method
        waypoints_dict = {'centerline': centerline}
        self._print_track_statistics(waypoints_dict)
